kind: Deployment
apiVersion: apps/v1
metadata:
  name: listvms
  namespace: myvms
  labels:
    app: listvms
    app.kubernetes.io/component: listvms
    app.kubernetes.io/instance: listvms
    app.kubernetes.io/part-of: listvms-app
    app.openshift.io/runtime-namespace: myvms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listvms
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: listvms
        deploymentconfig: listvms
    spec:
      containers:
        - name: listvms
          image: >-
            quay.io/markd/listvms
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
